# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=0)),
                ('zipCode', models.IntegerField(default=0)),
                ('prize_amount', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=32)),
            ],
        ),
    ]
